package br.com.poison.core;

import br.com.poison.core.util.extra.StringUtil;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class Constant {

    /* Server Constants */
    public static final String SERVER_NAME = System.getProperty("server_name", "Poison");
    public static final String SERVER_TITLE = "§a§l" + SERVER_NAME.toUpperCase();
    public static final String SERVER_PREFIX = SERVER_TITLE + " §7» §r";

    public static final String IP_DOMAIN = "poisonmc.com.br";

    public static final String WEBSITE = "www." + IP_DOMAIN;
    public static final String STORE = "loja." + IP_DOMAIN;
    public static final String DISCORD = "discord.gg/poisonmc";

    public static final String SLIME_HIKARI_SQL_LOADER = "hikariSql";


    /* Inventories */
    public static final String SIMULATOR_INVENTORY = "rO0ABXcEAAAAG3VyAAJbQqzzF/gGCFTgAgAAeHAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxL TS5KTCuxyizKz4vPSM3JTS1hZGB1zi/NK2FkYmBzScxNTE9lYGAAAMk6rGw0AAAAdXEAfgAAAAAA TB+LCAAAAAAAAADjYmDgYGDKTGGQzM3MS00uSkwrscosys+LT85ILS4pyEksSWVkYHXOL80rYWRi YHNJzE1MT2VgYAAAH4jQATgAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5K TCuxyizKz4vPSU1Pz8xLL2ZkYHXOL80rYWRiYHNJzE1MT2VgYAAA7APljzYAAAB1cQB+AAAAAABH H4sIAAAAAAAAAONiYOBgYMpMYRDJzcxLTS5KTCuxyizKz4tPys8vKWZkYHXOL80rYWRiYHNJzE1M T2VgYAAA6R5uMzMAAAB1cQB+AAAAAABBH4sIAAAAAAAAAONiYOBgYMpMYeDLzcxLTS5KTCuxSsov z2FkYHXOL80rcWBiYHNJzE1MT2VgYAAAv++QtS0AAAB1cQB+AAAAAABJH4sIAAAAAAAAAONiYOBg YMpMYRDLzcxLTS5KTCuxKkpNic8tLc4oys/PZWRgdc4vzStxYGJgc0nMTUxPZWBgAAC2ZHCoNQAA AHVxAH4AAAAAAEsfiwgAAAAAAAAA42Jg4GBgykxhkMjNzEtNLkpMK7FKKsovz4vPLS3OKMrPz2Vk YHXOL80rcWBiYHNJzE1MT2VgYAAAqPPYNDcAAAB1cQB+AAAAAABAH4sIAAAAAAAAAONiYOBgYMpM YeDNzcxLTS5KTCuxSqlMZWRgdc4vzStxYGJgc0nMTUxPZWBmAADWlWFDLAAAAHVxAH4AAAAAAEof iwgAAAAAAAAA42Jg4GBgykxhEM/NzEtNLkpMK7EqLsnPS40vyEzOTqxIZWRgdc4vzSthZGJgc0nM TUxPZWBgAAB2ls0ZNgAAAHVxAH4AAAAAAEgfiwgAAAAAAAAA42Jg4GBgykxhEM3NzEtNLkpMK7HK LMrPi89IzclNLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAAyTqsbDQAAAB1cQB+AAAAAABMH4sIAAAA AAAAAONiYOBgYMpMYZDMzcxLTS5KTCuxyizKz4tPzkgtLinISSxJZWRgdc4vzSthZGJgc0nMTUxP ZWBgAAAfiNABOAAAAHVxAH4AAAAAAEofiwgAAAAAAAAA42Jg4GBgykxhEM/NzEtNLkpMK7HKLMrP i89JTU/PzEsvZmRgdc4vzSthZGJgc0nMTUxPZWBgAADsA+WPNgAAAHVxAH4AAAAAAEcfiwgAAAAA AAAA42Jg4GBgykxhEMnNzEtNLkpMK7HKLMrPi0/Kzy8pZmRgdc4vzSthZGJgc0nMTUxPZWBgAADp Hm4zMwAAAHVxAH4AAAAAAEEfiwgAAAAAAAAA42Jg4GBgykxh4MvNzEtNLkpMK7FKyi/PYWRgdc4v zStxYGJgc0nMTUxPZWBgAAC/75C1LQAAAHVxAH4AAAAAAEkfiwgAAAAAAAAA42Jg4GBgykxhEMvN zEtNLkpMK7EqSk2Jzy0tzijKz89lZGB1zi/NK3FgYmBzScxNTE9lYGAAALZkcKg1AAAAdXEAfgAA AAAASx+LCAAAAAAAAADjYmDgYGDKTGGQyM3MS00uSkwrsUoqyi/Pi88tLc4oys/PZWRgdc4vzStx YGJgc0nMTUxPZWBgAACo89g0NwAAAHVxAH4AAAAAAEAfiwgAAAAAAAAA42Jg4GBgykxh4M3NzEtN LkpMK7FKqUxlZGB1zi/NK3FgYmBzScxNTE9lYGYAANaVYUMsAAAAdXEAfgAAAAAARh+LCAAAAAAA AADjYmDgYGDKTGEQzs3MS00uSkwrsSouyc9LjU+sSGVkYHXOL80rYWRiYHNJzE1MT2VgYAAAQU+5 2TIAAAB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxykksS4xPKk3OTi1h ZGB1zi/NK2FkYmBzScxNTE9lYGAAAAEaRN40AAAAdXEAfgAAAAAASB+LCAAAAAAAAADjYmDgYGDK TGEQzc3MS00uSkwrscpJLEuMTypNzk4tYWRgdc4vzSthZGJgc0nMTUxPZWBgAAABGkTeNAAAAHVx AH4AAAAAAEkfiwgAAAAAAAAA42Jg4GBgykxhEMvNzEtNLkpMK7EqTyxJLYpPKk3OTi1hZGB1zi/N K2FkYmBzScxNTE9lYGAAAApDDvU1AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83M S00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAA AAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2Fk YmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00u SkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAA Sh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBz ScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+LCAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwr scotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxNTE9lYGAAAJOMA8U2AAAAdXEAfgAAAAAASh+L CAAAAAAAAADjYmDgYGDKTGEQz83MS00uSkwrscotLc4oys/PjS8uSS1nZGB1zi/NK2FkYmBzScxN TE9lYGAAAJOMA8U2AAAA @ rO0ABXcEAAAACXVyAAJbQqzzF/gGCFTgAgAAeHAAAABuH4sIAAAAAAAAABWLQQ5AMBQFX1uEriyc xpYTuID8aFUTfqWK69PVZJIZDdSQ3qA7PNsl0pp6HwPP1xuiESiHcHMSGiqRa1BYXjYNQEio/dkz 891CQU/2JB+HcKUcQKIa6SBnf/sAliFrRGcAAAB1cQB+AAAAAABNH4sIAAAAAAAAAONiYOBgYMpM YZDKzcxLTS5KTCuxSs5PSspJLS7Jz0uNL0/MyWFkYHXOL80rcWBiYHNJzE1MT2VgYAAAnPlLjzkA AAB1cQB+AAAAAABIH4sIAAAAAAAAAONiYOBgYMpMYRDNzcxLTS5KTCuxykksS4xPKk3OTi1hZGB1 zi/NK2FkYmBzScxNTE9lYGAAAAEaRN40AAAAdXEAfgAAAAAASR+LCAAAAAAAAADjYmDgYGDKTGEQ y83MS00uSkwrsSpPLEktik8qTc5OLWFkYHXOL80rYWRiYHNJzE1MT2VgYAAACkMO9TUAAAB1cQB+ AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyi0tzijKz8+NLy5JLWdkYHXOL80r YWRiYHNJzE1MT2VgYAAAk4wDxTYAAAB1cQB+AAAAAABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxL TS5KTCuxyi0tzijKz8+NLy5JLWdkYHXOL80rYWRiYHNJzE1MT2VgYAAAk4wDxTYAAAB1cQB+AAAA AABKH4sIAAAAAAAAAONiYOBgYMpMYRDPzcxLTS5KTCuxyi0tzijKz8+NLy5JLWdkYHXOL80rYWRi YHNJzE1MT2VgYAAAk4wDxTYAAAB1cQB+AAAAAABAH4sIAAAAAAAAAONiYOBgYMpMYeDNzcxLTS5K TCuxKk9NYmRgdc4vzSthYWJgc0nMTUxPZWBgAACEsUNWLAAAAHVxAH4AAAAAAEMfiwgAAAAAAAAA 42Jg4GBgykxhEMjNzEtNLkpMK7EqyEnMyy5mZGB1zi/NK3FgYmBzScxNTE9lYGAAAHoppUgvAAAA";

    public static final String DEFAULT_ADDRESS = "0.0.0.0";
    public static final UUID CONSOLE_UUID = new UUID(0, 0);

    public static final List<UUID> CEO_IDS = new ArrayList<>();

    /* Redis Constants */
    public static final String REDIS_PROFILE_CHANNEL = "profile_update_channel";
    public static final String REDIS_CLAN_CHANNEL = "clan_update_channel";
    public static final String REDIS_SERVER_STATUS_CHANNEL = "server_status_channel";
    public static final String REDIS_SERVER_SENDER_CHANNEL = "server_sender_channel";

    public static final String REDIS_LEAGUE_UPDATE_CHANNEL = "league_update_channel";
    public static final String REDIS_ARCADE_CHANNEL = "arcade_channel";
    public static final String REDIS_CLAN_DELETE_CHANNEL = "clan_delete_channel";
    public static final String REDIS_TELEPORT_CHANNEL = "teleport_channel";

    public static final String[] REDIS_CHANNELS = new String[]{
            REDIS_PROFILE_CHANNEL, REDIS_CLAN_CHANNEL, REDIS_SERVER_STATUS_CHANNEL, REDIS_ARCADE_CHANNEL,
            REDIS_SERVER_SENDER_CHANNEL, REDIS_LEAGUE_UPDATE_CHANNEL, REDIS_CLAN_DELETE_CHANNEL,
            REDIS_TELEPORT_CHANNEL};

    /* Message Constant */
    public static final String BAN_TEMPLATE_MESSAGE = StringUtil.makeCenteredMessage(
            "§cSua conta foi %s banida.\n\n"
                    + "§cMotivo do banimento: %s\n"
                    + "%s"
                    + "§cID: #%s\n"
                    + "§cBanimento injusto? Contate-nos em: §e" + DISCORD + "\n");

    public static final String PROFILE_CREATE_FAILED = "§cNão foi possível carregar a sua conta!";

    public static final String WITHOUT_PERMISSION = "§cVocê não possui permissão para executar este comando!";

    /* Keys Constants */
    public static final String ROUTE_KEY = "route:";
    public static final String TELEPORT_KEY = "teleport:";

    /* Cooldown Constants */
    public static final String SKIN_COOLDOWN_KEY = "skin-cooldown";
    public static final String REPORT_COOLDOWN_KEY = "report-cooldown";
    public static final String CHAT_COOLDOWN_KEY = "chat-cooldown";

}
